### ISSUE TITLE
Работа с ключами

### ISSUE THREAD

**Issue by NIODER** [YbajaemiGroup/YWebsite#46]
Сделать две вьюшки для работы с ключами.

По нажатию на Создать открывается Окно создания токена. Прои нажатии на удалить Окно удаления.
![изображение](https://github.com/YbajaemiGroup/YWebsite/assets/91370096/2b43bcd8-4b0c-4821-b33c-68c5c70ab45c)

### Окно создания токена

![изображение](https://github.com/YbajaemiGroup/YWebsite/assets/91370096/80de720a-7875-40a6-9b34-314eb1299003)

### Окно удаления токена

![изображение](https://github.com/YbajaemiGroup/YWebsite/assets/91370096/03982a2d-6343-4afa-85c3-5ea21f6b01f5)

Пользователь вводит токен, в YApiInteractor надо написать функцию для работы с YClient по токенам (YApiInteractor просто прослойка).

**Comment by devokius** [comment]
Реализовано в 5998b4fd45c5edc0b4286694c13b24fcfe74f6c1
