### ISSUE TITLE
Рабочая облать Ссылки

### ISSUE THREAD

**Issue by NIODER** [YbajaemiGroup/YWebsite#48]
# Описание

Рабочая область позволяет управлять ссылками.

![изображение](https://github.com/YbajaemiGroup/YWebsite/assets/91370096/e08fafb9-a934-4cd2-ba61-070902193ad3)

## Userflow

![изображение](https://github.com/YbajaemiGroup/YWebsite/assets/91370096/85b5e62b-460b-4eee-b646-1fd2ff047f06)

## Рабочая область

![изображение](https://github.com/YbajaemiGroup/YWebsite/assets/91370096/107cd4f3-5454-4d0a-ab54-7ffda1dc4764)

### Поля

id - не изменяется пользователем (TextBlock)
id игрока - не изменяется пользователем (TextBlock). Клик правой открывает меню (ContextMenu) с кнопкой "Изменить", по нажатию этой кнопки открывается окно выбор игрока.
url - изменяется пользователем (TextBox)
description - изменяется пользователем (TextBox)

## Выбор игрока

![изображение](https://github.com/YbajaemiGroup/YWebsite/assets/91370096/103e009f-b813-4713-bba0-25dac2bdada0)

Список игроков из бд. Даблклик меняет id игрока.

## Код

Views: 
- UserControl (пользовательский элемент управления) - рабочая область.
- Window - диалоговое окно выбора игрока.

ViewModel - один на двух, Singleton, Locator

Открытие окна осуществляется посредством WindowService.

Model:
В YApiInteractor дописать медод по обновлению информации ссылки. (такого api нет - надо будет сначала удалить Link, потом создать новый с изменениями (если id будет меняться - ничего страшного).

Ветка уже есть

```
git fetch origin
git checkout issue#48
```

**Comment by devokius** [comment]
Реализовано в e652ee9af416bdf91307c013164f0c2430a147d4
